[tools]
poetry = "latest"
python = "3.14"

[tasks.lint]
description = "Lint code"
run = "poetry run ruff check beancount_n26/ tests/"

[tasks.test]
description = "Run tests"
run = "poetry run pytest tests/"
